### ISSUE TITLE
Chapter4: authenticationManagerBuilder.userDetailsService(userDetailsService)

### ISSUE THREAD

**Issue by JiashengHong** [habuma/spring-in-action-5-samples#100]
method userDetailsService in class org.springframework.security.config.annotation.authentication.builders.Authentic‌​ationManagerBuilder cannot be applied to given types; required: T found: tacos.service.UserDetailsService reason: inferred type does not conform to upper bound(s) inferred: tacos.service.UserDetailsService upper bound(s): org.springframework.security.core.userdetails.UserDetailsService

I followed the book but got this error.

By the way, I use spring-boot 2.4.1.

**Comment by minorsevenflatfive** [comment]
@JiashengHong I got the same problem, what's your solution for this?
