### ISSUE TITLE
chapter03-JPA Consider defining a bean of type 'com.example.tacos.IngredientRepository' in your configuration

### ISSUE THREAD

**Issue by lyqssb** [habuma/spring-in-action-5-samples#105]
Hi! I'm new here. I am trying to code like the book. But I met this:

> Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
[2m2021-06-25 15:31:10.483[0;39m [31mERROR[0;39m [35m35912[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36mo.s.b.d.LoggingFailureAnalysisReporter  [0;39m [2m:[0;39m 

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of constructor in com.example.tacos.controller.DesignController required a bean of type 'com.example.tacos.IngredientRepository' that could not be found.

Action:

Consider defining a bean of type 'com.example.tacos.IngredientRepository' in your configuration.
How can I fix this? @habuma

**Comment by Complex-2077** [comment]
I also encountered this problem. What should I do to fix it? >_<
