### ISSUE TITLE
the username, password, street, city, state.... are always null

### ISSUE THREAD

**Issue by aCodeRancher** [habuma/spring-in-action-5-samples#20]
No matter what I input in the registration.html form, those personal data are never posted to this RegistrationForm and they are always null.
https://github.com/habuma/spring-in-action-5-samples/blob/c016b0cc0fac7200e55e5172a810667c9fb495be/ch04/tacos/src/main/java/tacos/security/RegistrationForm.java#L20

**Comment by habuma** [comment]
My guess is that this is a byproduct of not having Lombok installed in your IDE. I'd wager that if you run it from the command line (`./mvnw clean package; java -jar target/tacocloud-0.0.4-SNAPSHOT.jar`) that it will work. Or if you were to install Lombok in your IDE, I'd bet it would work.

I'll leave this one open for now, pending more information.

**Comment by habuma** [comment]
Having no further information to go on, and having exercised this code myself many times tonight, I'm going to close this issue. If this is still a problem and there's more info to help debug it, please reopen and provide as much detail as possible.
