### ISSUE TITLE
Mention Lombok in README

### ISSUE THREAD

**Issue by habuma** [habuma/spring-in-action-5-samples#21]
The README files for all chapters (and/or the general README file for the repository) should mention Lombok and link to instructions for installing it in the reader's IDE.

**Comment by habuma** [comment]
I've added a general message about Lombok in the root README.adoc file. I may or may not add it to the individual chapter/project README files. I'll leave this issue open until I decide.

**Comment by habuma** [comment]
For now I'm going to close this issue. I still have plans to refine some of the README files. When I do that, I'll reconsider adding more info regarding Lombok.

**Comment by PankajJatav** [comment]
I have installed Lombok in your IDE. Still I am getting the error when i am hitting the /design url in chapter 2.
