### ISSUE TITLE
jsessionid parameter appended to URLs after submitting the design form

### ISSUE THREAD

**Issue by bifork** [habuma/spring-in-action-5-samples#27]
I didn't find this jsessionid parameter the first time I read the book. That was 
Spring Boot 2.0.4 of course. Now it's 2.0.6. 

Anybody else found the same issue? I didn't find it on another computer. Everything is the same except the macOS version. So this is strange.

**Comment by habuma** [comment]
I just tried it, both with Boot 2.0.4 and with 2.0.6. In neither case did I see the `jsessionid` parameter appear in the URLs. Very strange, indeed. 

Of course, as you probably know `jsessionid` is one of many means of managing session between requests. It often is handled in a cookie, but if cookies are disabled it might appear in a request parameter. Is it possible that you have cookies disabled in your browser?

**Comment by ghost** [comment]
I succeeded towards Chapter 6 before the final released edition. Seeing the final edition is out, I went back and started over again. Same computer, same OS, same browser. Issues kept popping out. I sometimes spend days researching an issue. Much like diagnosing Rails issues.
But could not afford more time. Moved on and quit the book. The OS, JDK, IDE, browsers were all reinstalled. I could not find the issues back.
