### ISSUE TITLE
Spring Security chapter no longer works for me

### ISSUE THREAD

**Issue by bifork** [habuma/spring-in-action-5-samples#28]
In normal mode of the browser, after I submit the register form, an HTTP Error 403 happens.
In private mode of the browser, after I submit the register form, I was taken to the design URL but the error shows the user object was null.

**Comment by habuma** [comment]
Hmmm...I assume that this is the issue you were referring to in issue #31. If so, may I close that issue and continue the discussion here?

As I stated in that issue, I was just able too run through chapter 4's code, register a user, login, order tacos, etc. Makes me wonder what's different for me than for you. By any chance do you have your code in a Git repo somewhere that I can poke at it and try it for myself? Or, if you are running the code from this repository, maybe you could do a screencast (not live...just a video recording) of it so I can watch what's going on. At this point, I have so little info to go on to know what problems you might be encountering.

**Comment by ghost** [comment]
I reinstalled everything and deleted the repo as well. Moved onto another course on udemy. Sorry. 
I did learn a lot of things when I finished the RESTful API chapters in a preview version of the book. So still many thanks. Wish you to achieve great improvements and successes in the future.
