### ISSUE TITLE
If you want to run Angular project in Ch6 at tacocloud-ui

### ISSUE THREAD

**Issue by Gxz-NGU** [habuma/spring-in-action-5-samples#29]
1. install `node.js` and V10.13.0 is OK for me.
2. install Angular CLI with `npm install -g @angular/cli`
3. run the project under tacocloud-ui path with `ng serve`  and then you will find the _**The serve command requires to be run in an Angular project, but a project definition could not be found.**_ with red color.
4. Don't be afraid.
5. Stackoverflow it and you should update your angular project to 7 while this project was still in 5.
6. update it and more details in https://stackoverflow.com/questions/52607924/have-a-new-project-but-when-ng-serve-i-get-error

> npm install -g npm-check-updates
> ncu -u
> ng update @angular/cli
> npm install

7. `ng serve` to fire it. And access browser with http://localhost:4200
8. recommend to read **Angular in Action by Jeremy Wilken (Manning, 2018)**. It's a awesome book for newer to study Angular.

**Comment by habuma** [comment]
Good point on items 1 and 2. I added that detail to the README at https://github.com/habuma/spring-in-action-5-samples/blob/master/ch06/README.adoc.

You should be able to build the entire project together, though, following the instructions in the README. The Maven build is written to handle the Angular stuff for you. 

That said, your remaining items are still good info in case someone wants to run the Angular stuff separately. And yes, absolutely pick up Angular in Action!

**Comment by Gxz-NGU** [comment]
Thanks for this affirmative answer. I was encouraged so much.

**Comment by habuma** [comment]
I'm going to close this issue. If there's anything else you think needs to be done in the context of the issue, please reopen and I'll consider it.
