### ISSUE TITLE
Ch.2 - missing this code on DesignTacoController class (filterByType error)

### ISSUE THREAD

**Issue by buddhabas** [habuma/spring-in-action-5-samples#30]
```
private List<Ingredient> filterByType(List<Ingredient> ingredients, Type type) {
		return ingredients.stream()
				.filter(x -> x.getType().equals(type))
				.collect(Collectors.toList());
```

**Comment by habuma** [comment]
Yes, I've had this added to the errata at https://manning-content.s3.amazonaws.com/download/2/cf76b1d-f831-4318-94aa-dc804d49f77c/Walls7_SpringIA_5E_err1.html. It should find its way into Livebook, updates to the ebook, and eventually future printings of the paper book. 

Given that it has been addressed as far as I am able to do so, I am going to close this issue now. Please feel free to reopen if you think there is more that can be done in regard to this issue.

**Comment by cgarrettjones** [comment]
the errata does not reflect buddhabas code and does not compile.

**Comment by mhadam** [comment]
@cgarrettjones you're right! funny enough, the errata is erroneous
