### ISSUE TITLE
Chapter1: image can not be loaded

### ISSUE THREAD

**Issue by Jerry4013** [habuma/spring-in-action-5-samples#42]
I follow the code in chapter 1, but the image cannot be display with this path. 
<img th:src="@{/images/Taco.jpg}"/>

**Comment by psprogis** [comment]
@Jerry4013, what path do you use ? Make user your image is located in src/main/resources/static/images folder.

**Comment by Jerry4013** [comment]
@psprogis Hi, I have solved this problem by changing to another img and refresh my project in STS. Thank you!
