### ISSUE TITLE
Ch07 - Add Ingredient with Traverson method throws 403 Forbidden error

### ISSUE THREAD

**Issue by MTamPham** [habuma/spring-in-action-5-samples#47]
I was trying to run the RestTemplate example but it halted in addIngredient() method and threw an exception while trying to post data to API. Would you explain to me the reason why I got it although the addAnIngredient() method was still working fine?

Thanks in advance

<img width="1204" alt="Screen Shot 2019-06-05 at 12 53 02 AM" src="https://user-images.githubusercontent.com/17444593/58921056-f168d180-872c-11e9-94da-02c72c0412ee.png">

**Comment by MTamPham** [comment]
I might do something wrong. His source code for this chapter is working well.

**Comment by wmcool** [comment]
I have encounted the same problem, how do you fix this?
