### ISSUE TITLE
Chapter 3. After chaning to JPA, got "Sequence "HIBERNATE_SEQUENCE" not found"

### ISSUE THREAD

**Issue by yeyypp** [habuma/spring-in-action-5-samples#54]
It appears at this line `Taco saved = tacoRepo.save(taco);`
I got data.sql and schema.sql in the resources file.
And add `spring.jpa.hibernate.ddl-auto=none` to avoid conflict

**Comment by dassio** [comment]
i still have this error even after adding the `spring.jpa.hibernate.ddl-auto=none`

**Comment by dassio** [comment]
i remove the `scheme.sq`l and change `spring.jpa.hibernate.ddl-auto=create-drop`. the `data.sql` is still there
