### ISSUE TITLE
Ch 3 JdbcTemplate: Failed to convert property value of type java.lang.String[] to required type java.util.List for property ingredients

### ISSUE THREAD

**Issue by Jason-TJW** [habuma/spring-in-action-5-samples#89]
Failed to convert property value of type java.lang.String[] to required type java.util.List for property ingredients; nested exception is java.lang.IllegalStateException: Cannot convert value of type java.lang.String to required type com.example.taco.Ingredient for property ingredients[0]: no matching editors or conversion strategy found

In design.html, the checkbox binds the value of ingredient.id, but it needs List<Ingredient> in Taco.java
When I update List<Ingredient> to List<String>, it works.

**Comment by Jason-TJW** [comment]
I used spring-boot 2.3.1
If used 2.0.4, it works fine.

**Comment by Nisf** [comment]
> Failed to convert property value of type java.lang.String[] to required type java.util.List for property ingredients; nested exception is java.lang.IllegalStateException: Cannot convert value of type java.lang.String to required type com.example.taco.Ingredient for property ingredients[0]: no matching editors or conversion strategy found
> 
> In design.html, the checkbox binds the value of ingredient.id, but it needs List in Taco.java
> When I update List to List, it works.

Hello, what does "update List to List" mean?  How should I change the code to solve the problem without chaning the version of spring-boot to 2.0.4. (ps: I am using spring-boot 2.3.8)
