### ISSUE TITLE
Chapter 3: h2-console does not find testdb

### ISSUE THREAD

**Issue by VPERepos** [habuma/spring-in-action-5-samples#90]
While trying  to log in under user:"sa" and password:"" I get an error message from h2-console:

Database "mem:testdb" not found, either pre-create it or allow remote database creation (not recommended in secure environments) [90149-200] 90149/90149

Is it necessary to make some steps, that are not mentioned in the book in order to create and access the testdb?

![Screenshot from 2020-08-03 20-37-00](https://user-images.githubusercontent.com/67160599/89215584-330f3980-d5c9-11ea-9670-8b4734b746a9.png)

Thanks in advance for any hints!

**Comment by VPERepos** [comment]
One has to add these lines to application.properties. 

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

**Comment by rakeshkumar4u** [comment]
> One has to add these lines to application.properties.
> 
> spring.datasource.url=jdbc:h2:mem:testdb spring.datasource.driverClassName=org.h2.Driver spring.datasource.username=sa spring.datasource.password=password spring.jpa.database-platform=org.hibernate.dialect.H2Dialect spring.h2.console.enabled=true

still not resolving the issue

**Comment by Bucephalus-lgtm** [comment]
That should be there in application.properties but most importantly you must have the following dependency in your build.gradle file:

`implementation 'org.springframework.boot:spring-boot-starter-jdbc'`

**Comment by upangka** [comment]
You need two dependencies. In addition to H2, you also need spring-boot-starter-data-jdbc. The configuration in Gradle should be as follows:
```java
dependencies {
   // ...
   implementation 'org.springframework.boot:spring-boot-starter-data-jdbc'
   implementation 'com.h2database:h2'
}
```
The application.yml configuration should be:
```
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
```
After successfully starting Spring Boot, you should see a log message indicating success:
```
H2 console available at '/h2-console'. Database available at 'jdbc:h2:mem:testdb'

```
